# Generated by Django 4.1.3 on 2023-01-10 22:33

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("wagtailcore", "0078_referenceindex"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterColumns",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("column_title", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SocialMediaSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facebook_page", models.URLField(blank=True, max_length=255)),
                ("twitter_page", models.URLField(blank=True, max_length=255)),
                ("linkedin_page", models.URLField(blank=True, max_length=255)),
                ("instagram_page", models.URLField(blank=True, max_length=255)),
                ("youtube_page", models.URLField(blank=True, max_length=255)),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Media Links",
            },
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Leave blank to use the page's URL.",
                        max_length=255,
                        verbose_name="Canonical URL",
                    ),
                ),
                (
                    "struct_org_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Organization", "Organization"),
                            ("Airline", "Organization > Airline"),
                            ("Corporation", "Organization > Corporation"),
                            (
                                "EducationalOrganization",
                                "Organization > EducationalOrganization",
                            ),
                            (
                                "CollegeOrUniversity",
                                "Organization > EducationalOrganization > CollegeOrUniversity",
                            ),
                            (
                                "ElementarySchool",
                                "Organization > EducationalOrganization > ElementarySchool",
                            ),
                            (
                                "HighSchool",
                                "Organization > EducationalOrganization > HighSchool",
                            ),
                            (
                                "MiddleSchool",
                                "Organization > EducationalOrganization > MiddleSchool",
                            ),
                            (
                                "Preschool",
                                "Organization > EducationalOrganization > Preschool",
                            ),
                            (
                                "School",
                                "Organization > EducationalOrganization > School",
                            ),
                            (
                                "GovernmentOrganization",
                                "Organization > GovernmentOrganization",
                            ),
                            ("LocalBusiness", "Organization > LocalBusiness"),
                            (
                                "AnimalShelter",
                                "Organization > LocalBusiness > AnimalShelter",
                            ),
                            (
                                "AutomotiveBusiness",
                                "Organization > LocalBusiness > AutomotiveBusiness",
                            ),
                            (
                                "AutoBodyShop",
                                "Organization > LocalBusiness > AutomotiveBusiness > AutoBodyShop",
                            ),
                            (
                                "AutoDealer",
                                "Organization > LocalBusiness > AutomotiveBusiness > AutoDealer",
                            ),
                            (
                                "AutoPartsStore",
                                "Organization > LocalBusiness > AutomotiveBusiness > AutoPartsStore",
                            ),
                            (
                                "AutoRental",
                                "Organization > LocalBusiness > AutomotiveBusiness > AutoRental",
                            ),
                            (
                                "AutoRepair",
                                "Organization > LocalBusiness > AutomotiveBusiness > AutoRepair",
                            ),
                            (
                                "AutoWash",
                                "Organization > LocalBusiness > AutomotiveBusiness > AutoWash",
                            ),
                            (
                                "GasStation",
                                "Organization > LocalBusiness > AutomotiveBusiness > GasStation",
                            ),
                            (
                                "MotorcycleDealer",
                                "Organization > LocalBusiness > AutomotiveBusiness > MotorcycleDealer",
                            ),
                            (
                                "MotorcycleRepair",
                                "Organization > LocalBusiness > AutomotiveBusiness > MotorcycleRepair",
                            ),
                            ("ChildCare", "Organization > LocalBusiness > ChildCare"),
                            ("Dentist", "Organization > LocalBusiness > Dentist"),
                            (
                                "DryCleaningOrLaundry",
                                "Organization > LocalBusiness > DryCleaningOrLaundry",
                            ),
                            (
                                "EmergencyService",
                                "Organization > LocalBusiness > EmergencyService",
                            ),
                            (
                                "FireStation",
                                "Organization > LocalBusiness > EmergencyService > FireStation",
                            ),
                            (
                                "Hospital",
                                "Organization > LocalBusiness > EmergencyService > Hospital",
                            ),
                            (
                                "PoliceStation",
                                "Organization > LocalBusiness > EmergencyService > PoliceStation",
                            ),
                            (
                                "EmploymentAgency",
                                "Organization > LocalBusiness > EmploymentAgency",
                            ),
                            (
                                "EntertainmentBusiness",
                                "Organization > LocalBusiness > EntertainmentBusiness",
                            ),
                            (
                                "AdultEntertainment",
                                "Organization > LocalBusiness > EntertainmentBusiness > AdultEntertainment",
                            ),
                            (
                                "AmusementPark",
                                "Organization > LocalBusiness > EntertainmentBusiness > AmusementPark",
                            ),
                            (
                                "ArtGallery",
                                "Organization > LocalBusiness > EntertainmentBusiness > ArtGallery",
                            ),
                            (
                                "Casino",
                                "Organization > LocalBusiness > EntertainmentBusiness > Casino",
                            ),
                            (
                                "ComedyClub",
                                "Organization > LocalBusiness > EntertainmentBusiness > ComedyClub",
                            ),
                            (
                                "MovieTheater",
                                "Organization > LocalBusiness > EntertainmentBusiness > MovieTheater",
                            ),
                            (
                                "NightClub",
                                "Organization > LocalBusiness > EntertainmentBusiness > NightClub",
                            ),
                            (
                                "FinancialService",
                                "Organization > LocalBusiness > FinancialService",
                            ),
                            (
                                "AccountingService",
                                "Organization > LocalBusiness > FinancialService > AccountingService",
                            ),
                            (
                                "AutomatedTeller",
                                "Organization > LocalBusiness > FinancialService > AutomatedTeller",
                            ),
                            (
                                "BankOrCreditUnion",
                                "Organization > LocalBusiness > FinancialService > BankOrCreditUnion",
                            ),
                            (
                                "InsuranceAgency",
                                "Organization > LocalBusiness > FinancialService > InsuranceAgency",
                            ),
                            (
                                "FoodEstablishment",
                                "Organization > LocalBusiness > FoodEstablishment",
                            ),
                            (
                                "Bakery",
                                "Organization > LocalBusiness > FoodEstablishment > Bakery",
                            ),
                            (
                                "BarOrPub",
                                "Organization > LocalBusiness > FoodEstablishment > BarOrPub",
                            ),
                            (
                                "Brewery",
                                "Organization > LocalBusiness > FoodEstablishment > Brewery",
                            ),
                            (
                                "CafeOrCoffeeShop",
                                "Organization > LocalBusiness > FoodEstablishment > CafeOrCoffeeShop",
                            ),
                            (
                                "FastFoodRestaurant",
                                "Organization > LocalBusiness > FoodEstablishment > FastFoodRestaurant",
                            ),
                            (
                                "IceCreamShop",
                                "Organization > LocalBusiness > FoodEstablishment > IceCreamShop",
                            ),
                            (
                                "Restaurant",
                                "Organization > LocalBusiness > FoodEstablishment > Restaurant",
                            ),
                            (
                                "Winery",
                                "Organization > LocalBusiness > FoodEstablishment > Winery",
                            ),
                            (
                                "GovernmentOffice",
                                "Organization > LocalBusiness > GovernmentOffice",
                            ),
                            (
                                "PostOffice",
                                "Organization > LocalBusiness > GovernmentOffice > PostOffice",
                            ),
                            (
                                "HealthAndBeautyBusiness",
                                "Organization > LocalBusiness > HealthAndBeautyBusiness",
                            ),
                            (
                                "BeautySalon",
                                "Organization > LocalBusiness > HealthAndBeautyBusiness > BeautySalon",
                            ),
                            (
                                "DaySpa",
                                "Organization > LocalBusiness > HealthAndBeautyBusiness > DaySpa",
                            ),
                            (
                                "HairSalon",
                                "Organization > LocalBusiness > HealthAndBeautyBusiness > HairSalon",
                            ),
                            (
                                "HealthClub",
                                "Organization > LocalBusiness > HealthAndBeautyBusiness > HealthClub",
                            ),
                            (
                                "NailSalon",
                                "Organization > LocalBusiness > HealthAndBeautyBusiness > NailSalon",
                            ),
                            (
                                "TattooParlor",
                                "Organization > LocalBusiness > HealthAndBeautyBusiness > TattooParlor",
                            ),
                            (
                                "HomeAndConstructionBusiness",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness",
                            ),
                            (
                                "Electrician",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness > Electrician",
                            ),
                            (
                                "GeneralContractor",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness > GeneralContractor",
                            ),
                            (
                                "HVACBusiness",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness > HVACBusiness",
                            ),
                            (
                                "HousePainter",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness > HousePainter",
                            ),
                            (
                                "Locksmith",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness > Locksmith",
                            ),
                            (
                                "MovingCompany",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness > MovingCompany",
                            ),
                            (
                                "Plumber",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness > Plumber",
                            ),
                            (
                                "RoofingContractor",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness > RoofingContractor",
                            ),
                            (
                                "InternetCafe",
                                "Organization > LocalBusiness > InternetCafe",
                            ),
                            (
                                "LegalService",
                                "Organization > LocalBusiness > LegalService",
                            ),
                            (
                                "Attorney",
                                "Organization > LocalBusiness > LegalService > Attorney",
                            ),
                            (
                                "Notary",
                                "Organization > LocalBusiness > LegalService > Notary",
                            ),
                            ("Library", "Organization > LocalBusiness > Library"),
                            (
                                "LodgingBusiness",
                                "Organization > LocalBusiness > LodgingBusiness",
                            ),
                            (
                                "BedAndBreakfast",
                                "Organization > LocalBusiness > LodgingBusiness > BedAndBreakfast",
                            ),
                            (
                                "Campground",
                                "Organization > LocalBusiness > LodgingBusiness > Campground",
                            ),
                            (
                                "Hostel",
                                "Organization > LocalBusiness > LodgingBusiness > Hostel",
                            ),
                            (
                                "Hotel",
                                "Organization > LocalBusiness > LodgingBusiness > Hotel",
                            ),
                            (
                                "Motel",
                                "Organization > LocalBusiness > LodgingBusiness > Motel",
                            ),
                            (
                                "Resort",
                                "Organization > LocalBusiness > LodgingBusiness > Resort",
                            ),
                            (
                                "ProfessionalService",
                                "Organization > LocalBusiness > ProfessionalService",
                            ),
                            (
                                "RadioStation",
                                "Organization > LocalBusiness > RadioStation",
                            ),
                            (
                                "RealEstateAgent",
                                "Organization > LocalBusiness > RealEstateAgent",
                            ),
                            (
                                "RecyclingCenter",
                                "Organization > LocalBusiness > RecyclingCenter",
                            ),
                            (
                                "SelfStorage",
                                "Organization > LocalBusiness > SelfStorage",
                            ),
                            (
                                "ShoppingCenter",
                                "Organization > LocalBusiness > ShoppingCenter",
                            ),
                            (
                                "SportsActivityLocation",
                                "Organization > LocalBusiness > SportsActivityLocation",
                            ),
                            (
                                "BowlingAlley",
                                "Organization > LocalBusiness > SportsActivityLocation > BowlingAlley",
                            ),
                            (
                                "ExerciseGym",
                                "Organization > LocalBusiness > SportsActivityLocation > ExerciseGym",
                            ),
                            (
                                "GolfCourse",
                                "Organization > LocalBusiness > SportsActivityLocation > GolfCourse",
                            ),
                            (
                                "HealthClub",
                                "Organization > LocalBusiness > SportsActivityLocation > HealthClub",
                            ),
                            (
                                "PublicSwimmingPool",
                                "Organization > LocalBusiness > SportsActivityLocation > PublicSwimmingPool",
                            ),
                            (
                                "SkiResort",
                                "Organization > LocalBusiness > SportsActivityLocation > SkiResort",
                            ),
                            (
                                "SportsClub",
                                "Organization > LocalBusiness > SportsActivityLocation > SportsClub",
                            ),
                            (
                                "StadiumOrArena",
                                "Organization > LocalBusiness > SportsActivityLocation > StadiumOrArena",
                            ),
                            (
                                "TennisComplex",
                                "Organization > LocalBusiness > SportsActivityLocation > TennisComplex",
                            ),
                            ("Store", "Organization > LocalBusiness > Store"),
                            (
                                "AutoPartsStore",
                                "Organization > LocalBusiness > Store > AutoPartsStore",
                            ),
                            (
                                "BikeStore",
                                "Organization > LocalBusiness > Store > BikeStore",
                            ),
                            (
                                "BookStore",
                                "Organization > LocalBusiness > Store > BookStore",
                            ),
                            (
                                "ClothingStore",
                                "Organization > LocalBusiness > Store > ClothingStore",
                            ),
                            (
                                "ComputerStore",
                                "Organization > LocalBusiness > Store > ComputerStore",
                            ),
                            (
                                "ConvenienceStore",
                                "Organization > LocalBusiness > Store > ConvenienceStore",
                            ),
                            (
                                "DepartmentStore",
                                "Organization > LocalBusiness > Store > DepartmentStore",
                            ),
                            (
                                "ElectronicsStore",
                                "Organization > LocalBusiness > Store > ElectronicsStore",
                            ),
                            (
                                "Florist",
                                "Organization > LocalBusiness > Store > Florist",
                            ),
                            (
                                "FurnitureStore",
                                "Organization > LocalBusiness > Store > FurnitureStore",
                            ),
                            (
                                "GardenStore",
                                "Organization > LocalBusiness > Store > GardenStore",
                            ),
                            (
                                "GroceryStore",
                                "Organization > LocalBusiness > Store > GroceryStore",
                            ),
                            (
                                "HardwareStore",
                                "Organization > LocalBusiness > Store > HardwareStore",
                            ),
                            (
                                "HobbyShop",
                                "Organization > LocalBusiness > Store > HobbyShop",
                            ),
                            (
                                "HomeGoodsStore",
                                "Organization > LocalBusiness > Store > HomeGoodsStore",
                            ),
                            (
                                "JewelryStore",
                                "Organization > LocalBusiness > Store > JewelryStore",
                            ),
                            (
                                "LiquorStore",
                                "Organization > LocalBusiness > Store > LiquorStore",
                            ),
                            (
                                "MensClothingStore",
                                "Organization > LocalBusiness > Store > MensClothingStore",
                            ),
                            (
                                "MobilePhoneStore",
                                "Organization > LocalBusiness > Store > MobilePhoneStore",
                            ),
                            (
                                "MovieRentalStore",
                                "Organization > LocalBusiness > Store > MovieRentalStore",
                            ),
                            (
                                "MusicStore",
                                "Organization > LocalBusiness > Store > MusicStore",
                            ),
                            (
                                "OfficeEquipmentStore",
                                "Organization > LocalBusiness > Store > OfficeEquipmentStore",
                            ),
                            (
                                "OutletStore",
                                "Organization > LocalBusiness > Store > OutletStore",
                            ),
                            (
                                "PawnShop",
                                "Organization > LocalBusiness > Store > PawnShop",
                            ),
                            (
                                "PetStore",
                                "Organization > LocalBusiness > Store > PetStore",
                            ),
                            (
                                "ShoeStore",
                                "Organization > LocalBusiness > Store > ShoeStore",
                            ),
                            (
                                "SportingGoodsStore",
                                "Organization > LocalBusiness > Store > SportingGoodsStore",
                            ),
                            (
                                "TireShop",
                                "Organization > LocalBusiness > Store > TireShop",
                            ),
                            (
                                "ToyStore",
                                "Organization > LocalBusiness > Store > ToyStore",
                            ),
                            (
                                "WholesaleStore",
                                "Organization > LocalBusiness > Store > WholesaleStore",
                            ),
                            (
                                "TelevisionStation",
                                "Organization > LocalBusiness > TelevisionStation",
                            ),
                            (
                                "TouristInformationCenter",
                                "Organization > LocalBusiness > TouristInformationCenter",
                            ),
                            (
                                "TravelAgency",
                                "Organization > LocalBusiness > TravelAgency",
                            ),
                            (
                                "MedicalOrganization",
                                "Organization > MedicalOrganization",
                            ),
                            ("Dentist", "Organization > MedicalOrganization > Dentist"),
                            (
                                "Hospital",
                                "Organization > MedicalOrganization > Hospital",
                            ),
                            (
                                "Pharmacy",
                                "Organization > MedicalOrganization > Pharmacy",
                            ),
                            (
                                "Physician",
                                "Organization > MedicalOrganization > Physician",
                            ),
                            ("NGO", "Organization > NGO"),
                            ("PerformingGroup", "Organization > PerformingGroup"),
                            (
                                "DanceGroup",
                                "Organization > PerformingGroup > DanceGroup",
                            ),
                            (
                                "MusicGroup",
                                "Organization > PerformingGroup > MusicGroup",
                            ),
                            (
                                "TheaterGroup",
                                "Organization > PerformingGroup > TheaterGroup",
                            ),
                            ("SportsOrganization", "Organization > SportsOrganization"),
                            (
                                "SportsTeam",
                                "Organization > SportsOrganization > SportsTeam",
                            ),
                        ],
                        default="",
                        help_text="If blank, no structured data will be used on this page.",
                        max_length=255,
                        verbose_name="Organization type",
                    ),
                ),
                (
                    "struct_org_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Leave blank to use the site name in Settings > Sites",
                        max_length=255,
                        verbose_name="Organization name",
                    ),
                ),
                (
                    "struct_org_phone",
                    models.CharField(
                        blank=True,
                        help_text="Include country code for best results. For example: +1-216-555-8000",
                        max_length=255,
                        verbose_name="Telephone number",
                    ),
                ),
                (
                    "struct_org_address_street",
                    models.CharField(
                        blank=True,
                        help_text="House number and street. For example, 55 Public Square Suite 1710",
                        max_length=255,
                        verbose_name="Street address",
                    ),
                ),
                (
                    "struct_org_address_locality",
                    models.CharField(
                        blank=True,
                        help_text="City or locality. For example, Cleveland",
                        max_length=255,
                        verbose_name="City",
                    ),
                ),
                (
                    "struct_org_address_region",
                    models.CharField(
                        blank=True,
                        help_text="State, province, county, or region. For example, OH",
                        max_length=255,
                        verbose_name="State",
                    ),
                ),
                (
                    "struct_org_address_postal",
                    models.CharField(
                        blank=True,
                        help_text="Zip or postal code. For example, 44113",
                        max_length=255,
                        verbose_name="Postal code",
                    ),
                ),
                (
                    "struct_org_address_country",
                    models.CharField(
                        blank=True,
                        help_text="For example, USA. Two-letter ISO 3166-1 alpha-2 country code is also acceptable https://en.wikipedia.org/wiki/ISO_3166-1",
                        max_length=255,
                        verbose_name="Country",
                    ),
                ),
                (
                    "struct_org_geo_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        verbose_name="Geographic latitude",
                    ),
                ),
                (
                    "struct_org_geo_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        verbose_name="Geographic longitude",
                    ),
                ),
                (
                    "struct_org_hours",
                    wagtail.fields.StreamField(
                        [
                            (
                                "hours",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "days",
                                            wagtail.blocks.MultipleChoiceBlock(
                                                choices=[
                                                    ("Monday", "Monday"),
                                                    ("Tuesday", "Tuesday"),
                                                    ("Wednesday", "Wednesday"),
                                                    ("Thursday", "Thursday"),
                                                    ("Friday", "Friday"),
                                                    ("Saturday", "Saturday"),
                                                    ("Sunday", "Sunday"),
                                                ],
                                                help_text="For late night hours past 23:59, define each day in a separate block.",
                                                verbose_name="Days",
                                            ),
                                        ),
                                        (
                                            "start_time",
                                            wagtail.blocks.TimeBlock(
                                                verbose_name="Opening time"
                                            ),
                                        ),
                                        (
                                            "end_time",
                                            wagtail.blocks.TimeBlock(
                                                verbose_name="Closing time"
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        use_json_field=True,
                        verbose_name="Hours of operation",
                    ),
                ),
                (
                    "struct_org_actions",
                    wagtail.fields.StreamField(
                        [
                            (
                                "actions",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "action_type",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("OrderAction", "OrderAction"),
                                                    ("ReserveAction", "ReserveAction"),
                                                ],
                                                verbose_name="Action Type",
                                            ),
                                        ),
                                        (
                                            "target",
                                            wagtail.blocks.URLBlock(
                                                verbose_name="Target URL"
                                            ),
                                        ),
                                        (
                                            "language",
                                            wagtail.blocks.CharBlock(
                                                default="en-US",
                                                help_text="If the action is offered in multiple languages, create separate actions for each language.",
                                                verbose_name="Language",
                                            ),
                                        ),
                                        (
                                            "result_type",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("Reservation", "Reservation"),
                                                    (
                                                        "BusReservation",
                                                        "BusReservation",
                                                    ),
                                                    (
                                                        "EventReservation",
                                                        "EventReservation",
                                                    ),
                                                    (
                                                        "FlightReservation",
                                                        "FlightReservation",
                                                    ),
                                                    (
                                                        "FoodEstablishmentReservation",
                                                        "FoodEstablishmentReservation",
                                                    ),
                                                    (
                                                        "LodgingReservation",
                                                        "LodgingReservation",
                                                    ),
                                                    (
                                                        "RentalCarReservation",
                                                        "RentalCarReservation",
                                                    ),
                                                    (
                                                        "ReservationPackage",
                                                        "ReservationPackage",
                                                    ),
                                                    (
                                                        "TaxiReservation",
                                                        "TaxiReservation",
                                                    ),
                                                    (
                                                        "TrainReservation",
                                                        "TrainReservation",
                                                    ),
                                                ],
                                                help_text="Leave blank for OrderAction",
                                                required=False,
                                                verbose_name="Result Type",
                                            ),
                                        ),
                                        (
                                            "result_name",
                                            wagtail.blocks.CharBlock(
                                                help_text='Example: "Reserve a table", "Book an appointment", etc.',
                                                required=False,
                                                verbose_name="Result Name",
                                            ),
                                        ),
                                        (
                                            "extra_json",
                                            wagtail.blocks.RawHTMLBlock(
                                                form_classname="monospace",
                                                help_text="Additional JSON-LD inserted into the Action dictionary. Must be properties of https://schema.org/Action.",
                                                required=False,
                                                verbose_name="Additional action markup",
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        use_json_field=True,
                        verbose_name="Actions",
                    ),
                ),
                (
                    "struct_org_extra_json",
                    models.TextField(
                        blank=True,
                        help_text="Additional JSON-LD inserted into the Organization dictionary. Must be properties of https://schema.org/Organization or the selected organization type.",
                        verbose_name="Additional Organization markup",
                    ),
                ),
                (
                    "header_title",
                    models.CharField(
                        default="Custom and precision sheet metal", max_length=255
                    ),
                ),
                ("header_description", models.TextField(blank=True, null=True)),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Shown when linking to this page on social media.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Preview image",
                    ),
                ),
                (
                    "struct_org_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="A photo of the facility. This photo will be cropped to 1:1, 4:3, and 16:9 aspect ratios automatically.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Photo of Organization",
                    ),
                ),
                (
                    "struct_org_logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank to use the logo in Settings > Layout > Logo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Organization logo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="FooterLinksSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Link",
                "verbose_name_plural": "Footer Links",
                "db_table": "footer_links",
            },
        ),
        migrations.CreateModel(
            name="FooterLinks",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("text", models.CharField(max_length=100, null=True)),
                ("link", models.URLField(max_length=255)),
                ("new_tab", models.BooleanField(default=False)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footer_links",
                        to="prometal.footercolumns",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="footercolumns",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="footer_columns",
                to="prometal.footerlinkssettings",
            ),
        ),
        migrations.CreateModel(
            name="ContactUsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Leave blank to use the page's URL.",
                        max_length=255,
                        verbose_name="Canonical URL",
                    ),
                ),
                (
                    "struct_org_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Organization", "Organization"),
                            ("Airline", "Organization > Airline"),
                            ("Corporation", "Organization > Corporation"),
                            (
                                "EducationalOrganization",
                                "Organization > EducationalOrganization",
                            ),
                            (
                                "CollegeOrUniversity",
                                "Organization > EducationalOrganization > CollegeOrUniversity",
                            ),
                            (
                                "ElementarySchool",
                                "Organization > EducationalOrganization > ElementarySchool",
                            ),
                            (
                                "HighSchool",
                                "Organization > EducationalOrganization > HighSchool",
                            ),
                            (
                                "MiddleSchool",
                                "Organization > EducationalOrganization > MiddleSchool",
                            ),
                            (
                                "Preschool",
                                "Organization > EducationalOrganization > Preschool",
                            ),
                            (
                                "School",
                                "Organization > EducationalOrganization > School",
                            ),
                            (
                                "GovernmentOrganization",
                                "Organization > GovernmentOrganization",
                            ),
                            ("LocalBusiness", "Organization > LocalBusiness"),
                            (
                                "AnimalShelter",
                                "Organization > LocalBusiness > AnimalShelter",
                            ),
                            (
                                "AutomotiveBusiness",
                                "Organization > LocalBusiness > AutomotiveBusiness",
                            ),
                            (
                                "AutoBodyShop",
                                "Organization > LocalBusiness > AutomotiveBusiness > AutoBodyShop",
                            ),
                            (
                                "AutoDealer",
                                "Organization > LocalBusiness > AutomotiveBusiness > AutoDealer",
                            ),
                            (
                                "AutoPartsStore",
                                "Organization > LocalBusiness > AutomotiveBusiness > AutoPartsStore",
                            ),
                            (
                                "AutoRental",
                                "Organization > LocalBusiness > AutomotiveBusiness > AutoRental",
                            ),
                            (
                                "AutoRepair",
                                "Organization > LocalBusiness > AutomotiveBusiness > AutoRepair",
                            ),
                            (
                                "AutoWash",
                                "Organization > LocalBusiness > AutomotiveBusiness > AutoWash",
                            ),
                            (
                                "GasStation",
                                "Organization > LocalBusiness > AutomotiveBusiness > GasStation",
                            ),
                            (
                                "MotorcycleDealer",
                                "Organization > LocalBusiness > AutomotiveBusiness > MotorcycleDealer",
                            ),
                            (
                                "MotorcycleRepair",
                                "Organization > LocalBusiness > AutomotiveBusiness > MotorcycleRepair",
                            ),
                            ("ChildCare", "Organization > LocalBusiness > ChildCare"),
                            ("Dentist", "Organization > LocalBusiness > Dentist"),
                            (
                                "DryCleaningOrLaundry",
                                "Organization > LocalBusiness > DryCleaningOrLaundry",
                            ),
                            (
                                "EmergencyService",
                                "Organization > LocalBusiness > EmergencyService",
                            ),
                            (
                                "FireStation",
                                "Organization > LocalBusiness > EmergencyService > FireStation",
                            ),
                            (
                                "Hospital",
                                "Organization > LocalBusiness > EmergencyService > Hospital",
                            ),
                            (
                                "PoliceStation",
                                "Organization > LocalBusiness > EmergencyService > PoliceStation",
                            ),
                            (
                                "EmploymentAgency",
                                "Organization > LocalBusiness > EmploymentAgency",
                            ),
                            (
                                "EntertainmentBusiness",
                                "Organization > LocalBusiness > EntertainmentBusiness",
                            ),
                            (
                                "AdultEntertainment",
                                "Organization > LocalBusiness > EntertainmentBusiness > AdultEntertainment",
                            ),
                            (
                                "AmusementPark",
                                "Organization > LocalBusiness > EntertainmentBusiness > AmusementPark",
                            ),
                            (
                                "ArtGallery",
                                "Organization > LocalBusiness > EntertainmentBusiness > ArtGallery",
                            ),
                            (
                                "Casino",
                                "Organization > LocalBusiness > EntertainmentBusiness > Casino",
                            ),
                            (
                                "ComedyClub",
                                "Organization > LocalBusiness > EntertainmentBusiness > ComedyClub",
                            ),
                            (
                                "MovieTheater",
                                "Organization > LocalBusiness > EntertainmentBusiness > MovieTheater",
                            ),
                            (
                                "NightClub",
                                "Organization > LocalBusiness > EntertainmentBusiness > NightClub",
                            ),
                            (
                                "FinancialService",
                                "Organization > LocalBusiness > FinancialService",
                            ),
                            (
                                "AccountingService",
                                "Organization > LocalBusiness > FinancialService > AccountingService",
                            ),
                            (
                                "AutomatedTeller",
                                "Organization > LocalBusiness > FinancialService > AutomatedTeller",
                            ),
                            (
                                "BankOrCreditUnion",
                                "Organization > LocalBusiness > FinancialService > BankOrCreditUnion",
                            ),
                            (
                                "InsuranceAgency",
                                "Organization > LocalBusiness > FinancialService > InsuranceAgency",
                            ),
                            (
                                "FoodEstablishment",
                                "Organization > LocalBusiness > FoodEstablishment",
                            ),
                            (
                                "Bakery",
                                "Organization > LocalBusiness > FoodEstablishment > Bakery",
                            ),
                            (
                                "BarOrPub",
                                "Organization > LocalBusiness > FoodEstablishment > BarOrPub",
                            ),
                            (
                                "Brewery",
                                "Organization > LocalBusiness > FoodEstablishment > Brewery",
                            ),
                            (
                                "CafeOrCoffeeShop",
                                "Organization > LocalBusiness > FoodEstablishment > CafeOrCoffeeShop",
                            ),
                            (
                                "FastFoodRestaurant",
                                "Organization > LocalBusiness > FoodEstablishment > FastFoodRestaurant",
                            ),
                            (
                                "IceCreamShop",
                                "Organization > LocalBusiness > FoodEstablishment > IceCreamShop",
                            ),
                            (
                                "Restaurant",
                                "Organization > LocalBusiness > FoodEstablishment > Restaurant",
                            ),
                            (
                                "Winery",
                                "Organization > LocalBusiness > FoodEstablishment > Winery",
                            ),
                            (
                                "GovernmentOffice",
                                "Organization > LocalBusiness > GovernmentOffice",
                            ),
                            (
                                "PostOffice",
                                "Organization > LocalBusiness > GovernmentOffice > PostOffice",
                            ),
                            (
                                "HealthAndBeautyBusiness",
                                "Organization > LocalBusiness > HealthAndBeautyBusiness",
                            ),
                            (
                                "BeautySalon",
                                "Organization > LocalBusiness > HealthAndBeautyBusiness > BeautySalon",
                            ),
                            (
                                "DaySpa",
                                "Organization > LocalBusiness > HealthAndBeautyBusiness > DaySpa",
                            ),
                            (
                                "HairSalon",
                                "Organization > LocalBusiness > HealthAndBeautyBusiness > HairSalon",
                            ),
                            (
                                "HealthClub",
                                "Organization > LocalBusiness > HealthAndBeautyBusiness > HealthClub",
                            ),
                            (
                                "NailSalon",
                                "Organization > LocalBusiness > HealthAndBeautyBusiness > NailSalon",
                            ),
                            (
                                "TattooParlor",
                                "Organization > LocalBusiness > HealthAndBeautyBusiness > TattooParlor",
                            ),
                            (
                                "HomeAndConstructionBusiness",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness",
                            ),
                            (
                                "Electrician",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness > Electrician",
                            ),
                            (
                                "GeneralContractor",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness > GeneralContractor",
                            ),
                            (
                                "HVACBusiness",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness > HVACBusiness",
                            ),
                            (
                                "HousePainter",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness > HousePainter",
                            ),
                            (
                                "Locksmith",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness > Locksmith",
                            ),
                            (
                                "MovingCompany",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness > MovingCompany",
                            ),
                            (
                                "Plumber",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness > Plumber",
                            ),
                            (
                                "RoofingContractor",
                                "Organization > LocalBusiness > HomeAndConstructionBusiness > RoofingContractor",
                            ),
                            (
                                "InternetCafe",
                                "Organization > LocalBusiness > InternetCafe",
                            ),
                            (
                                "LegalService",
                                "Organization > LocalBusiness > LegalService",
                            ),
                            (
                                "Attorney",
                                "Organization > LocalBusiness > LegalService > Attorney",
                            ),
                            (
                                "Notary",
                                "Organization > LocalBusiness > LegalService > Notary",
                            ),
                            ("Library", "Organization > LocalBusiness > Library"),
                            (
                                "LodgingBusiness",
                                "Organization > LocalBusiness > LodgingBusiness",
                            ),
                            (
                                "BedAndBreakfast",
                                "Organization > LocalBusiness > LodgingBusiness > BedAndBreakfast",
                            ),
                            (
                                "Campground",
                                "Organization > LocalBusiness > LodgingBusiness > Campground",
                            ),
                            (
                                "Hostel",
                                "Organization > LocalBusiness > LodgingBusiness > Hostel",
                            ),
                            (
                                "Hotel",
                                "Organization > LocalBusiness > LodgingBusiness > Hotel",
                            ),
                            (
                                "Motel",
                                "Organization > LocalBusiness > LodgingBusiness > Motel",
                            ),
                            (
                                "Resort",
                                "Organization > LocalBusiness > LodgingBusiness > Resort",
                            ),
                            (
                                "ProfessionalService",
                                "Organization > LocalBusiness > ProfessionalService",
                            ),
                            (
                                "RadioStation",
                                "Organization > LocalBusiness > RadioStation",
                            ),
                            (
                                "RealEstateAgent",
                                "Organization > LocalBusiness > RealEstateAgent",
                            ),
                            (
                                "RecyclingCenter",
                                "Organization > LocalBusiness > RecyclingCenter",
                            ),
                            (
                                "SelfStorage",
                                "Organization > LocalBusiness > SelfStorage",
                            ),
                            (
                                "ShoppingCenter",
                                "Organization > LocalBusiness > ShoppingCenter",
                            ),
                            (
                                "SportsActivityLocation",
                                "Organization > LocalBusiness > SportsActivityLocation",
                            ),
                            (
                                "BowlingAlley",
                                "Organization > LocalBusiness > SportsActivityLocation > BowlingAlley",
                            ),
                            (
                                "ExerciseGym",
                                "Organization > LocalBusiness > SportsActivityLocation > ExerciseGym",
                            ),
                            (
                                "GolfCourse",
                                "Organization > LocalBusiness > SportsActivityLocation > GolfCourse",
                            ),
                            (
                                "HealthClub",
                                "Organization > LocalBusiness > SportsActivityLocation > HealthClub",
                            ),
                            (
                                "PublicSwimmingPool",
                                "Organization > LocalBusiness > SportsActivityLocation > PublicSwimmingPool",
                            ),
                            (
                                "SkiResort",
                                "Organization > LocalBusiness > SportsActivityLocation > SkiResort",
                            ),
                            (
                                "SportsClub",
                                "Organization > LocalBusiness > SportsActivityLocation > SportsClub",
                            ),
                            (
                                "StadiumOrArena",
                                "Organization > LocalBusiness > SportsActivityLocation > StadiumOrArena",
                            ),
                            (
                                "TennisComplex",
                                "Organization > LocalBusiness > SportsActivityLocation > TennisComplex",
                            ),
                            ("Store", "Organization > LocalBusiness > Store"),
                            (
                                "AutoPartsStore",
                                "Organization > LocalBusiness > Store > AutoPartsStore",
                            ),
                            (
                                "BikeStore",
                                "Organization > LocalBusiness > Store > BikeStore",
                            ),
                            (
                                "BookStore",
                                "Organization > LocalBusiness > Store > BookStore",
                            ),
                            (
                                "ClothingStore",
                                "Organization > LocalBusiness > Store > ClothingStore",
                            ),
                            (
                                "ComputerStore",
                                "Organization > LocalBusiness > Store > ComputerStore",
                            ),
                            (
                                "ConvenienceStore",
                                "Organization > LocalBusiness > Store > ConvenienceStore",
                            ),
                            (
                                "DepartmentStore",
                                "Organization > LocalBusiness > Store > DepartmentStore",
                            ),
                            (
                                "ElectronicsStore",
                                "Organization > LocalBusiness > Store > ElectronicsStore",
                            ),
                            (
                                "Florist",
                                "Organization > LocalBusiness > Store > Florist",
                            ),
                            (
                                "FurnitureStore",
                                "Organization > LocalBusiness > Store > FurnitureStore",
                            ),
                            (
                                "GardenStore",
                                "Organization > LocalBusiness > Store > GardenStore",
                            ),
                            (
                                "GroceryStore",
                                "Organization > LocalBusiness > Store > GroceryStore",
                            ),
                            (
                                "HardwareStore",
                                "Organization > LocalBusiness > Store > HardwareStore",
                            ),
                            (
                                "HobbyShop",
                                "Organization > LocalBusiness > Store > HobbyShop",
                            ),
                            (
                                "HomeGoodsStore",
                                "Organization > LocalBusiness > Store > HomeGoodsStore",
                            ),
                            (
                                "JewelryStore",
                                "Organization > LocalBusiness > Store > JewelryStore",
                            ),
                            (
                                "LiquorStore",
                                "Organization > LocalBusiness > Store > LiquorStore",
                            ),
                            (
                                "MensClothingStore",
                                "Organization > LocalBusiness > Store > MensClothingStore",
                            ),
                            (
                                "MobilePhoneStore",
                                "Organization > LocalBusiness > Store > MobilePhoneStore",
                            ),
                            (
                                "MovieRentalStore",
                                "Organization > LocalBusiness > Store > MovieRentalStore",
                            ),
                            (
                                "MusicStore",
                                "Organization > LocalBusiness > Store > MusicStore",
                            ),
                            (
                                "OfficeEquipmentStore",
                                "Organization > LocalBusiness > Store > OfficeEquipmentStore",
                            ),
                            (
                                "OutletStore",
                                "Organization > LocalBusiness > Store > OutletStore",
                            ),
                            (
                                "PawnShop",
                                "Organization > LocalBusiness > Store > PawnShop",
                            ),
                            (
                                "PetStore",
                                "Organization > LocalBusiness > Store > PetStore",
                            ),
                            (
                                "ShoeStore",
                                "Organization > LocalBusiness > Store > ShoeStore",
                            ),
                            (
                                "SportingGoodsStore",
                                "Organization > LocalBusiness > Store > SportingGoodsStore",
                            ),
                            (
                                "TireShop",
                                "Organization > LocalBusiness > Store > TireShop",
                            ),
                            (
                                "ToyStore",
                                "Organization > LocalBusiness > Store > ToyStore",
                            ),
                            (
                                "WholesaleStore",
                                "Organization > LocalBusiness > Store > WholesaleStore",
                            ),
                            (
                                "TelevisionStation",
                                "Organization > LocalBusiness > TelevisionStation",
                            ),
                            (
                                "TouristInformationCenter",
                                "Organization > LocalBusiness > TouristInformationCenter",
                            ),
                            (
                                "TravelAgency",
                                "Organization > LocalBusiness > TravelAgency",
                            ),
                            (
                                "MedicalOrganization",
                                "Organization > MedicalOrganization",
                            ),
                            ("Dentist", "Organization > MedicalOrganization > Dentist"),
                            (
                                "Hospital",
                                "Organization > MedicalOrganization > Hospital",
                            ),
                            (
                                "Pharmacy",
                                "Organization > MedicalOrganization > Pharmacy",
                            ),
                            (
                                "Physician",
                                "Organization > MedicalOrganization > Physician",
                            ),
                            ("NGO", "Organization > NGO"),
                            ("PerformingGroup", "Organization > PerformingGroup"),
                            (
                                "DanceGroup",
                                "Organization > PerformingGroup > DanceGroup",
                            ),
                            (
                                "MusicGroup",
                                "Organization > PerformingGroup > MusicGroup",
                            ),
                            (
                                "TheaterGroup",
                                "Organization > PerformingGroup > TheaterGroup",
                            ),
                            ("SportsOrganization", "Organization > SportsOrganization"),
                            (
                                "SportsTeam",
                                "Organization > SportsOrganization > SportsTeam",
                            ),
                        ],
                        default="",
                        help_text="If blank, no structured data will be used on this page.",
                        max_length=255,
                        verbose_name="Organization type",
                    ),
                ),
                (
                    "struct_org_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Leave blank to use the site name in Settings > Sites",
                        max_length=255,
                        verbose_name="Organization name",
                    ),
                ),
                (
                    "struct_org_phone",
                    models.CharField(
                        blank=True,
                        help_text="Include country code for best results. For example: +1-216-555-8000",
                        max_length=255,
                        verbose_name="Telephone number",
                    ),
                ),
                (
                    "struct_org_address_street",
                    models.CharField(
                        blank=True,
                        help_text="House number and street. For example, 55 Public Square Suite 1710",
                        max_length=255,
                        verbose_name="Street address",
                    ),
                ),
                (
                    "struct_org_address_locality",
                    models.CharField(
                        blank=True,
                        help_text="City or locality. For example, Cleveland",
                        max_length=255,
                        verbose_name="City",
                    ),
                ),
                (
                    "struct_org_address_region",
                    models.CharField(
                        blank=True,
                        help_text="State, province, county, or region. For example, OH",
                        max_length=255,
                        verbose_name="State",
                    ),
                ),
                (
                    "struct_org_address_postal",
                    models.CharField(
                        blank=True,
                        help_text="Zip or postal code. For example, 44113",
                        max_length=255,
                        verbose_name="Postal code",
                    ),
                ),
                (
                    "struct_org_address_country",
                    models.CharField(
                        blank=True,
                        help_text="For example, USA. Two-letter ISO 3166-1 alpha-2 country code is also acceptable https://en.wikipedia.org/wiki/ISO_3166-1",
                        max_length=255,
                        verbose_name="Country",
                    ),
                ),
                (
                    "struct_org_geo_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        verbose_name="Geographic latitude",
                    ),
                ),
                (
                    "struct_org_geo_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        verbose_name="Geographic longitude",
                    ),
                ),
                (
                    "struct_org_hours",
                    wagtail.fields.StreamField(
                        [
                            (
                                "hours",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "days",
                                            wagtail.blocks.MultipleChoiceBlock(
                                                choices=[
                                                    ("Monday", "Monday"),
                                                    ("Tuesday", "Tuesday"),
                                                    ("Wednesday", "Wednesday"),
                                                    ("Thursday", "Thursday"),
                                                    ("Friday", "Friday"),
                                                    ("Saturday", "Saturday"),
                                                    ("Sunday", "Sunday"),
                                                ],
                                                help_text="For late night hours past 23:59, define each day in a separate block.",
                                                verbose_name="Days",
                                            ),
                                        ),
                                        (
                                            "start_time",
                                            wagtail.blocks.TimeBlock(
                                                verbose_name="Opening time"
                                            ),
                                        ),
                                        (
                                            "end_time",
                                            wagtail.blocks.TimeBlock(
                                                verbose_name="Closing time"
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        use_json_field=True,
                        verbose_name="Hours of operation",
                    ),
                ),
                (
                    "struct_org_actions",
                    wagtail.fields.StreamField(
                        [
                            (
                                "actions",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "action_type",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("OrderAction", "OrderAction"),
                                                    ("ReserveAction", "ReserveAction"),
                                                ],
                                                verbose_name="Action Type",
                                            ),
                                        ),
                                        (
                                            "target",
                                            wagtail.blocks.URLBlock(
                                                verbose_name="Target URL"
                                            ),
                                        ),
                                        (
                                            "language",
                                            wagtail.blocks.CharBlock(
                                                default="en-US",
                                                help_text="If the action is offered in multiple languages, create separate actions for each language.",
                                                verbose_name="Language",
                                            ),
                                        ),
                                        (
                                            "result_type",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("Reservation", "Reservation"),
                                                    (
                                                        "BusReservation",
                                                        "BusReservation",
                                                    ),
                                                    (
                                                        "EventReservation",
                                                        "EventReservation",
                                                    ),
                                                    (
                                                        "FlightReservation",
                                                        "FlightReservation",
                                                    ),
                                                    (
                                                        "FoodEstablishmentReservation",
                                                        "FoodEstablishmentReservation",
                                                    ),
                                                    (
                                                        "LodgingReservation",
                                                        "LodgingReservation",
                                                    ),
                                                    (
                                                        "RentalCarReservation",
                                                        "RentalCarReservation",
                                                    ),
                                                    (
                                                        "ReservationPackage",
                                                        "ReservationPackage",
                                                    ),
                                                    (
                                                        "TaxiReservation",
                                                        "TaxiReservation",
                                                    ),
                                                    (
                                                        "TrainReservation",
                                                        "TrainReservation",
                                                    ),
                                                ],
                                                help_text="Leave blank for OrderAction",
                                                required=False,
                                                verbose_name="Result Type",
                                            ),
                                        ),
                                        (
                                            "result_name",
                                            wagtail.blocks.CharBlock(
                                                help_text='Example: "Reserve a table", "Book an appointment", etc.',
                                                required=False,
                                                verbose_name="Result Name",
                                            ),
                                        ),
                                        (
                                            "extra_json",
                                            wagtail.blocks.RawHTMLBlock(
                                                form_classname="monospace",
                                                help_text="Additional JSON-LD inserted into the Action dictionary. Must be properties of https://schema.org/Action.",
                                                required=False,
                                                verbose_name="Additional action markup",
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        use_json_field=True,
                        verbose_name="Actions",
                    ),
                ),
                (
                    "struct_org_extra_json",
                    models.TextField(
                        blank=True,
                        help_text="Additional JSON-LD inserted into the Organization dictionary. Must be properties of https://schema.org/Organization or the selected organization type.",
                        verbose_name="Additional Organization markup",
                    ),
                ),
                (
                    "contact_form_title",
                    models.CharField(default="Get in touch", max_length=255),
                ),
                (
                    "contact_form_description",
                    models.CharField(
                        default="Our friendly team would love to hear from you.",
                        max_length=255,
                    ),
                ),
                (
                    "submit_button_text",
                    models.CharField(default="Send message", max_length=255),
                ),
                (
                    "company_location_latitude",
                    models.CharField(default="42.302032967279764", max_length=255),
                ),
                (
                    "company_location_longitude",
                    models.CharField(default="21.207894876779495", max_length=255),
                ),
                (
                    "company_pin_text",
                    models.CharField(default="ProMetal SH.P.K.", max_length=255),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Shown when linking to this page on social media.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Preview image",
                    ),
                ),
                (
                    "struct_org_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="A photo of the facility. This photo will be cropped to 1:1, 4:3, and 16:9 aspect ratios automatically.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Photo of Organization",
                    ),
                ),
                (
                    "struct_org_logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank to use the logo in Settings > Layout > Logo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Organization logo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ContactInformationSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("website_url", models.URLField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=100)),
                ("phone_no", models.CharField(blank=True, max_length=100)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Information",
            },
        ),
    ]
